CREATE TABLE bill (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	price FLOAT UNSIGNED NOT NULL,
	type ENUM('CREDIT', 'DEBIT') DEFAULT 'CREDIT',
	user_id INT UNSIGNED NOT NULL
)ENGINE=InnoDB;
