<p>
	<a href="<?php echo $this->url(array('controller' => 'bills', 'action' => 'add'), '', true); ?>" class="button white">Add New</a>
</p>

<table class="grid">
	<thead>
		<tr>
			<th scope="col" style="width: 13%;">Id</th>
			<th scope="col">Title</th>
			<th scope="col" style="width: 25%;">Price</th>
			<th scope="col" style="width: 17%;">Actions</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="4" style="text-align: right">
				<div class="total">
					<div class="debit">
						Total of Debits: <?php echo $this->currency($this->balance->getDebit()); ?>
					</div>
					<div class="credit">
						Total of Credits: <?php echo $this->currency($this->balance->getCredit()); ?>
					</div>
					<div class="balance">
						<b>Balance:</b> <span class="<?php echo $this->balance->getBalanceType(); ?>"><?php echo $this->currency($this->balance->getBalance()); ?></span>
					</div>
				</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
		<?php if (sizeof($this->balance->getBills()) <= 0): ?>
		<tr>
			<td colspan="4">No finances found.</td>
		</tr>
		<?php else: ?>
		<?php foreach ($this->balance->getBills() as $bill): ?>
		<tr>
			<td><?php echo $bill->getId(); ?></td>
			<td><?php echo $bill->getTitle(); ?></td>
			<td><?php echo $this->currency($bill->getPrice()); ?></td>
			<td>
				<a href="<?php echo $this->url(array('controller' => 'bills', 'action' => 'edit', 'id' => $bill->getId()), '', true); ?>">Edit</a>
				 &nbsp; 
				<a href="<?php echo $this->url(array('controller' => 'bills', 'action' => 'delete', 'id' => $bill->getId()), '', true); ?>" onclick="if (!window.confirm('Are you sure?')) return false;">Delete</a>
			</td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</tbody>
</table>